### ISSUE TITLE
BTCPay synchronization issue

### ISSUE THREAD

**Issue by blacksocket** [mynodebtc/mynode_docs#63]
Dear All,

I have setup "mynode" v0.3.35 server on PROXMOX VM with BTCPay Server >> 1.11.2 and having synching issues below. Seems it is not starting the synchronization. I am bit lost in all these configuration files..

![Image](https://github.com/user-attachments/assets/1aafbadf-c5a0-442c-9745-8b15d4f8b93f)

root@mynode:/mnt/hdd/mynode/btcpayserver# free -h
............. total used free shared buff/cache available
Mem: 7.8Gi 2.7Gi 131Mi 65Mi 5.3Gi 5.1Gi
Swap: 2.0Gi 43Mi 2.0Gi

root@mynode:/mnt/hdd/mynode/btcpayserver# df -h
Filesystem Size Used Avail Use% Mounted on
udev 3.9G 0 3.9G 0% /dev
tmpfs 794M 16M 779M 2% /run
/dev/sda1 32G 11G 19G 37% /
tmpfs 3.9G 0 3.9G 0% /dev/shm
tmpfs 5.0M 0 5.0M 0% /run/lock
log2ram 40M 7.0M 34M 18% /var/log
/dev/sdb1 1.7T 823G 803G 51% /mnt/hdd
tmpfs 794M 12K 794M 1% /run/user/109
overlay 1.7T 823G 803G 51% /mnt/hdd/mynode/docker/overlay2/462c205c8b3076d13ea32c3bdd99329e9aafd3dc21155e0f641b73526dda517d/merged
tmpfs 794M 8.0K 794M 1% /run/user/1001
overlay 1.7T 823G 803G 51% /mnt/hdd/mynode/docker/overlay2/60db6877d6ed00bd63abe1fcdb17b6ad5c0fbc6a0803bea0a6214e44f0b178d6/merged
overlay 1.7T 823G 803G 51% /mnt/hdd/mynode/docker/overlay2/633fdd97080debe4c04b4c4a2920d684e89634aa1fb45e89e971dad6626894e6/merged
overlay 1.7T 823G 803G 51% /mnt/hdd/mynode/docker/overlay2/6cc2181b63c47d306fb85e4bb2131c3980140b66f12e1282feb76b9b1f3c4660/merged

----------------

root@mynode:/mnt/hdd/mynode/btcpayserver# docker ps
CONTAINER ID IMAGE COMMAND CREATED STATUS PORTS NAMES
0f8f8029e6cf btcpayserver/btcpayserver:1.11.2 "/app/docker-entrypo…" 43 minutes ago Up 43 minutes 0.0.0.0:49392->49392/tcp, [::]:49392->49392/tcp generated_btcpayserver_1

a10990e2449b nicolasdorier/nbxplorer:2.5.25 "dotnet NBXplorer.dll" 43 minutes ago Up 43 minutes 32838/tcp generated_nbxplorer_1

514a4632a56c btcpayserver/postgres:13.18 "/migrate-docker-ent…" 43 minutes ago Up 43 minutes 5432/tcp generated_postgres_1

--------------

root@mynode:/mnt/hdd/mynode/btcpayserver# docker logs -f a10990e2449b
info: Configuration: NBXplorer version 2.5.25
info: Configuration: Data Directory: /datadir
info: Configuration: Configuration File: /datadir/Main/settings.config
info: Configuration: Network: Mainnet
info: Configuration: Supported chains: BTC
info: Configuration: Network: Mainnet
info: Configuration: Supported chains: BTC
info: NBXplorer.DatabaseSetup: Postgres services activated
info: Explorer: Trimming the event table if needed...
fail: NBXplorer.Indexer.BTC: Unhandled exception in the indexer, retrying in 0 seconds
System.Net.Sockets.SocketException (111): Connection refused
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
at System.Net.Sockets.Socket.g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
at NBitcoin.Protocol.Connectors.DefaultEndpointConnector.ConnectSocket(Socket socket, EndPoint endpoint, NodeConnectionParameters nodeConnectionParameters, CancellationToken cancellationToken)
at NBitcoin.Protocol.Node.ConnectAsync(Network network, EndPoint endpoint, NetworkAddress peer, NodeConnectionParameters parameters)
at NBXplorer.Backend.Indexer.ConnectNode(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 292
at NBXplorer.Backend.Indexer.IndexerLoopCore(CancellationToken token) in /source/NBXplorer/Backend/Indexer.cs:line 146
at NBXplorer.Backend.Indexer.IndexerLoop() in /source/NBXplorer/Backend/Indexer.cs:line 95

--------------

root@mynode:/mnt/hdd/mynode/btcpayserver# docker logs -f 0f8f8029e6cf
bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)
info: Configuration: Data Directory: /datadir
info: Configuration: Configuration File: /datadir/Main/settings.config
info: BTCPayServer.Plugins.PluginManager: Loading plugins from /root/.btcpayserver/Plugins
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer - 1.11.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Shopify - 1.11.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PointOfSale - 1.11.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.PayButton - 1.11.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.NFC - 1.11.2
info: BTCPayServer.Plugins.PluginManager: Adding and executing plugin BTCPayServer.Plugins.Crowdfund - 1.11.2
info: Configuration: Supported chains: BTC
info: Configuration: BTC: Explorer url is http://nbxplorer:32838/
info: Configuration: BTC: Cookie file is /root/.nbxplorer/Main/.cookie
info: Configuration: Network: Mainnet
info: Configuration: LogFile: /datadir/btcpay.log
info: Configuration: Log Level: Debug
info: Configuration: Root Path: /
info: Configuration: Connection to NBXplorer's database successful, dashboard and reporting features activated.
info: PayServer: Checking if any payment arrived on lightning while the server was offline...
info: PayServer: Processing lightning payments...
info: PayServer: Starting listening NBXplorer (BTC)
info: PayServer: Start watching invoices
info: PayServer: Starting payment request expiration watcher
info: PayServer: 0 pending payment requests being checked since last run
info: Configuration: Now listening on: http://0.0.0.0:49392/

---------------

Logs from BTCPay GUI below:

2025-05-06 20:57:43.669 +00:00 [INF] Root Path: /
2025-05-06 20:57:44.109 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2025-05-06 20:57:44.150 +00:00 [INF] Checking if any payment arrived on lightning while the server was offline...
2025-05-06 20:57:44.197 +00:00 [INF] Processing lightning payments...
2025-05-06 20:57:44.233 +00:00 [INF] Starting listening NBXplorer (BTC)
2025-05-06 20:57:44.248 +00:00 [INF] Start watching invoices
2025-05-06 21:47:48.771 +00:00 [INF] DelayedTransactionBroadcasterHostedService successfully exited...
2025-05-06 21:47:48.771 +00:00 [INF] TorServices successfully exited...
2025-05-06 21:47:48.772 +00:00 [INF] CheckConfigurationHostedService successfully exited...
2025-05-06 21:47:48.777 +00:00 [INF] PullPaymentHostedService successfully exited...
2025-05-06 21:47:54.737 +00:00 [ERR] BTC: NBXplorer error `Name or service not known (nbxplorer:32838)`
2025-05-06 21:47:54.740 +00:00 [ERR] BTC: NBXplorer error `Name or service not known (nbxplorer:32838)`
2025-05-06 21:48:18.766 +00:00 [INF] NBXplorerListener successfully exited...
2025-05-06 21:48:18.768 +00:00 [INF] LightningListener successfully exited...
2025-05-06 21:48:18.774 +00:00 [INF] LightningPendingPayoutListener successfully exited...
2025-05-06 21:48:18.775 +00:00 [INF] Stop watching invoices
2025-05-06 21:48:18.783 +00:00 [INF] RatesHostedService successfully exited...
2025-05-06 21:48:18.786 +00:00 [INF] DynamicDnsHostedService successfully exited...
2025-05-06 21:48:18.786 +00:00 [INF] DbMigrationsHostedService successfully exited...
2025-05-06 21:51:42.915 +00:00 [INF] Running the migration scripts...
2025-05-06 21:51:43.743 +00:00 [INF] No migrations were applied. The database is already up to date.
2025-05-06 21:51:43.744 +00:00 [INF] All migration scripts ran successfully
2025-05-06 21:51:44.045 +00:00 [INF] Root Path: /
2025-05-06 21:51:44.503 +00:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2025-05-06 21:51:44.544 +00:00 [INF] Checking if any payment arrived on lightning while the server was offline...
2025-05-06 21:51:44.603 +00:00 [INF] Processing lightning payments...
2025-05-06 21:51:44.644 +00:00 [INF] Starting listening NBXplorer (BTC)
2025-05-06 21:51:44.664 +00:00 [INF] Start watching invoices

-----------

root@mynode:/mnt/hdd/mynode/btcpayserver# docker exec -it a10990e2449b bash

root@a10990e2449b:/app# env
HOSTNAME=a10990e2449b
NBXPLORER_BIND=0.0.0.0:32838
DOTNET_VERSION=8.0.11
APP_UID=1654
PWD=/app
NBXPLORER_BTCRPCUSER=mynode
HOME=/root
NBXPLORER_BTCRPCPASSWORD=password
ASPNETCORE_HTTP_PORTS=8080
NBXPLORER_POSTGRES=User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorermainnet
TERM=xterm
SHLVL=1
ASPNET_VERSION=8.0.11
DOTNET_RUNNING_IN_CONTAINER=true
NBXPLORER_DATADIR=/datadir
NBXPLORER_TRIMEVENTS=10000
NBXPLORER_BTCNODEENDPOINT=host.docker.internal:8333
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
NBXPLORER_SIGNALFILESDIR=/datadir
NBXPLORER_CHAINS=btc
NBXPLORER_NETWORK=mainnet
NBXPLORER_BTCRPCURL=http://host.docker.internal:8332/
_=/usr/bin/env

Could you please help with this issue ?

Many Thanks for All the support!

**Comment by blacksocket** [comment]
root@mynode:/mnt/hdd/mynode/btcpayserver# cat /mnt/hdd/mynode/btcpayserver/btcpayserver-docker/Generated/docker-compose.generated.yml

```
version: "3"
services:
  btcpayserver:
    restart: unless-stopped
    container_name: generated_btcpayserver_1
    image: ${BTCPAY_IMAGE:-btcpayserver/btcpayserver:2.1.1}
    expose:
    - "49392"
    environment:
      BTCPAY_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=btcpayserver;Database=btcpayserver${NBITCOIN_NETWORK:-regtest}
      BTCPAY_EXPLORERPOSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=btcpayserver;MaxPoolSize=80;Database=nbxplorer${NBITCOIN_NETWORK:-regtest}
      BTCPAY_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      BTCPAY_BIND: 0.0.0.0:49392
      BTCPAY_ROOTPATH: ${BTCPAY_ROOTPATH:-/}
      BTCPAY_SSHCONNECTION: "root@host.docker.internal"
      BTCPAY_SSHTRUSTEDFINGERPRINTS: ${BTCPAY_SSHTRUSTEDFINGERPRINTS}
      BTCPAY_SSHKEYFILE: ${BTCPAY_SSHKEYFILE}
      BTCPAY_SSHAUTHORIZEDKEYS: ${BTCPAY_SSHAUTHORIZEDKEYS}
      BTCPAY_DEBUGLOG: btcpay.log
      BTCPAY_UPDATEURL: https://api.github.com/repos/btcpayserver/btcpayserver/releases/latest
      BTCPAY_DOCKERDEPLOYMENT: "true"
      BTCPAY_CHAINS: "btc"
      BTCPAY_BTCEXPLORERURL: http://nbxplorer:32838/
      BTCPAY_BTCLIGHTNING: "type=lnd-rest;server=https://host.docker.internal:10080/;macaroonfilepath=/etc/lnd_bitcoin/data/chain/bitcoin/mainnet/admin.macaroon;allowinsecure=true"
      BTCPAY_BTCEXTERNALLNDGRPC: "server=/;macaroonfilepath=/etc/lnd_bitcoin/data/chain/bitcoin/mainnet/admin.macaroon;macaroondirectorypath=/etc/lnd_bitcoin/data/chain/bitcoin/mainnet"
      BTCPAY_BTCEXTERNALLNDREST: "server=/lnd-rest/btc/;macaroonfilepath=/etc/lnd_bitcoin/data/chain/bitcoin/mainnet/admin.macaroon;macaroondirectorypath=/etc/lnd_bitcoin/data/chain/bitcoin/mainnet"
      BTCPAY_BTCEXTERNALLNDSEEDBACKUP: "/etc/lnd_bitcoin/data/chain/bitcoin/${NBITCOIN_NETWORK:-regtest}/walletunlock.json"
    labels:
      traefik.enable: "true"
      traefik.http.routers.btcpayserver.rule: Host(`${BTCPAY_HOST}`)
    links:
    - postgres
    volumes:
    - "btcpay_datadir:/datadir"
    - "nbxplorer_datadir:/root/.nbxplorer"
    - "btcpay_pluginsdir:/root/.btcpayserver/Plugins"
    - "/mnt/hdd/mynode/lnd:/etc/lnd_bitcoin"
    ports:
    - "${NOREVERSEPROXY_HTTP_PORT:-80}:49392"
    extra_hosts:
    - "host.docker.internal:172.17.0.1"
  nbxplorer:
    restart: unless-stopped
    container_name: generated_nbxplorer_1
    image: nicolasdorier/nbxplorer:2.5.25
    expose:
    - "32838"
    environment:
      NBXPLORER_NETWORK: ${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_BIND: 0.0.0.0:32838
      NBXPLORER_TRIMEVENTS: 10000
      NBXPLORER_SIGNALFILESDIR: /datadir
      NBXPLORER_POSTGRES: User ID=postgres;Host=postgres;Port=5432;Application Name=nbxplorer;MaxPoolSize=20;Database=nbxplorer${NBITCOIN_NETWORK:-regtest}
      NBXPLORER_CHAINS: "btc"
      NBXPLORER_BTCRPCURL: http://host.docker.internal:8332/
      NBXPLORER_BTCNODEENDPOINT: host.docker.internal:8333
    links:
    - postgres
    volumes:
    - "nbxplorer_datadir:/datadir"
    - "/mnt/hdd/mynode/bitcoin:/root/.bitcoin"
    env_file:
    - nbxplorer-variables.env
    extra_hosts:
    - "host.docker.internal:172.17.0.1"
  postgres:
    restart: unless-stopped
    container_name: generated_postgres_1
    shm_size: 256mb
    image: btcpayserver/postgres:13.18
    command: ["-c", "random_page_cost=1.0", "-c", "shared_preload_libraries=pg_stat_statements"]
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
    - "postgres_datadir:/var/lib/postgresql/data"
volumes:
  btcpay_datadir:
  btcpay_pluginsdir:
  nbxplorer_datadir:
  postgres_datadir:
networks: {}
```
